beerclub/urls.py
from django.conf.urls import include, url
from beerclub.views import AccountListView, LegendsListView, BeerListView, DrinkCreateView, AccountCreateView, StockView, BeerUniqueListView, RootView, StatsView, HistoryView
from django.contrib.auth.decorators import login_required

from beerclub import rest as bc_rest

urlpatterns = [
    url(r'^accounts/$', AccountListView.as_view(), name='accounts'),
    url(r'^legends/$', LegendsListView.as_view(), name='legends' ),
    url(r'^beers/$', BeerListView.as_view(), name='beers' ),
    url(r'^beers/unique/$', BeerUniqueListView.as_view(), name='beers_unique' ),
    url(r'^drink/create/$', DrinkCreateView.as_view(), name='drink' ),
    url(r'^populate/$', AccountCreateView.as_view(), name='populate' ),
    url(r'^stock/import/$', StockView.as_view(), name='stockimport'),
    url(r'^stats/$', StatsView.as_view(), name='stats'),
    url(r'^stats/(?P<year>.+)/$', StatsView.as_view(), name='stats_year'),
    url(r'^history/$', HistoryView.as_view(), name='history'),
    # Django rest api
    # Definetly used
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/beer_list/', bc_rest.beer_list, name='beer_list'),
    url(r'^api/beer_search_instock/(?P<term>.+)/', bc_rest.beer_search_instock, name='beer_search_instock'),
    url(r'^api/beer_search/(?P<term>.+)/', bc_rest.beer_search, name='beer_search'),
    url(r'^api/beer_detail_barcode/(?P<barcode>.+)/', bc_rest.beer_detail_barcode, name='beer_detail_barcode'),
    url(r'^api/account_self_serve/', bc_rest.account_self_serve, name='account_self_serve'),
    url(r'^api/account/(?P<id>.+)/', bc_rest.account, name='account_id'),
    url(r'^api/account_unique_available/(?P<id>.+)/', bc_rest.account_unique_available, name='account_unique_available_id'),
    url(r'^api/account_drunk/(?P<acc_id>.+)/(?P<beer_id>.+)/', bc_rest.account_drunk, name='account_drunk'),
    url(r'^api/account_search/(?P<term>.+)/', bc_rest.account_search, name='account_search'),
    #Maybe unused?
    url(r'^api/account_unique_available/', bc_rest.account_unique_available, name='account_unique_available'),
    url(r'^api/account_random_unique/', bc_rest.account_random_unique, name='account_random_unique'),
    url(r'^api/account/', bc_rest.account, name='account'),
    url(r'^api/account_drinks/', bc_rest.account_drinks, name='account_drinks'),
    url(r'^api/beer_detail/(?P<id>.+)/', bc_rest.beer_detail, name='beer_detail'),
    url(r'^api/account_current_drink/', bc_rest.account_current_drink, name='account_current_drink'),
    url(r'^api/account_current_drink_rating/', bc_rest.account_current_drink_rating, name='account_current_drink_rating'),
    # Root view
    url(r'^', RootView.as_view(), name='root'),
]

its_django/urls.py
from django.conf.urls import include, url

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
admin.autodiscover()
#from django.views.generic import TemplateView
from beerclub.views import RootView

urlpatterns = [
    # Examples:
    # url(r'^$', 'its_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/', auth_views.login, {'template_name': 'beerclub/login.html', 'extra_context': {'next':'/bc/'} }, name="accounts_login"),
    url(r'^accounts/logout/', auth_views.logout, {'next_page': '/', 'template_name': 'beerclub/logout.html'}, name="accounts_logout"),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^bc/', include('beerclub.urls', namespace='beerclub')),
    url(r'^', include('beerclub.urls', namespace='beerclub_root')),
    #url(r'^$', 'django.contrib.auth.views.login', {'template_name': 'beerclub/login.html', 'extra_context': {'next':'/bc/'} }, name="root_accounts_login"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beerclub/models.py
from django.db import models
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from datetime import timedelta, date
from django.utils import timezone

class Brewery(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    country = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]

class Beer(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    brewery = models.ForeignKey(Brewery)
    abvp = models.FloatField(default=0, blank=True, null=True)

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('beerclub:beer_update', kwargs={'pk' : self.id})

class BeerInst(models.Model):
    beer = models.ForeignKey(Beer)
    container = models.CharField(max_length=8, choices=(
        ('can', 'can'),
        ('bottle' , 'bottle'),
        ('horn' , 'horn'),
        ('glass' , 'glass'),
        ), help_text="Packaging the beer comes in."
    )
    volume = models.IntegerField()
    unit_sale_price = models.IntegerField(help_text="This is a value in AU cents", default=400)
    #cost_price = models.IntegerField(help_text="This is a value in AU cents")
    special = models.BooleanField(default=False)
    barcode = models.CharField(max_length=50, null=True, blank=True, unique=True, db_index=True, default=None)
    barcode_pack = models.CharField(max_length=50, null=True, blank=True, db_index=True, default=None)
    quantity_pack = models.PositiveIntegerField(null=True, blank=True, default=6)
    stock_total = models.IntegerField(default=0)
    stock_value = models.IntegerField(default=0)

    class Meta:
        ordering = ["beer__name"]

    def __unicode__(self):
        return '%s, %s (%s) %sml' % (self.beer.name, self.beer.brewery.name,
            self.container, self.volume)

    def drink_set_year(self):
        return self.drink_set.filter(date__year=date.today().year)

    def get_absolute_url(self):
        return reverse('beerclub:beerinst_update', kwargs={'pk' : self.id})

    @property
    def volume_ethanol(self):
        if (self.volume == None) or (self.beer.abvp == None):
            return 0
        else:
            return self.volume * (self.beer.abvp / 100.0)

    def reconcile_stock(self):
        total_imported = self.stock_set.all().aggregate(quantity=models.Sum('quantity'))['quantity']
        total_writeoff = self.stockwriteoff_set.all().aggregate(quantity=models.Sum('quantity'))['quantity']
        if total_imported is None:
            total_imported = 0
        if total_writeoff is None:
            total_writeoff = 0
        total_sold = self.drink_set.count()
        self.stock_total = total_imported - (total_sold + total_writeoff)
        self.stock_value = self.stock_total * self.unit_sale_price
        #print(self.stock_total)
        self.save()

    def clean(self):
        if self.barcode == '':
            self.barcode = None
        if self.barcode_pack == '':
            self.barcode_pack = None

class Stock(models.Model):
    # How many beers were imported to the office at some date.
    beerinst = models.ForeignKey(BeerInst)
    quantity = models.IntegerField(default=0)
    datetime = models.DateTimeField(auto_now=True, db_index=True)
    comment = models.CharField(max_length=500, blank=True, null=True)

    def __unicode__(self):
        return "%s %s : %s" % (self.datetime, self.beerinst, self.comment)

    class Meta:
        ordering = ["-datetime"]

class StockTake(models.Model):
    """
        This is a short lived temporal model just used to calculate the set of beers
        In stock from the ones not.
        The main reason for this is a way to do set changes and stock fix ups
    """
    beerinst = models.ForeignKey(BeerInst)
    quantity = models.IntegerField(default=0)

    def __unicode__(self):
        return "%s : %s" % (self.beerinst, self.quantity)

class StockWriteOff(models.Model):
    beerinst = models.ForeignKey(BeerInst)
    quantity = models.IntegerField(default=0)
    datetime = models.DateTimeField(auto_now=True, db_index=True)
    comment = models.CharField(max_length=500)

    def __unicode__(self):
        return "%s %s : %s" % (self.datetime, self.beerinst, self.comment)

    class Meta:
        ordering = ["-datetime"]

class Account(models.Model):
    user = models.ForeignKey(User)
    balance = models.IntegerField(help_text="This is a value in AU cents. It is reconciled as a set of payments and drinks")
    #barcode = models.CharField(max_length=50, null=True, blank=True, unique=True, db_index=True)
    #special_due = models.IntegerField(default=0)
    class Meta:
        ordering = ["user__first_name"]
        permissions = (("can_login", "Can login"),)

    @property
    def active(self):
        year_past = date.today() - timedelta(days=366)
        num_drinks = self.drink_set.filter(date__gt=year_past).count()
        if num_drinks > 0:
            return True
        return False

    @property
    def drinks_had(self):
        spec_drinks = self.drink_set.filter(date__year=date.today().year).values_list('beerinst__beer__id', flat=True)
        return len(spec_drinks)

    def drinks_unique_had_year(self, stat_year=None):
        if stat_year is None:
            stat_year = date.today().year
        spec_drinks = self.drink_set.filter(date__year=stat_year).values_list('beerinst__beer__id', flat=True).distinct()
        return len(spec_drinks)

    @property
    def drinks_unique_had(self, stat_year=None):
        return self.drinks_unique_had_year()

    @property
    def drinks_volume(self):
        spec_drinks = self.drink_set.filter(date__year=date.today().year).values_list('beerinst__volume', flat=True)
        return reduce(lambda x, y: x + y, spec_drinks, 0)

    @property
    def drinks_ethanol_volume(self):
        spec_drinks = self.drink_set.filter(date__year=date.today().year)
        ethanol_volumes = map(lambda drink: drink.beerinst.volume_ethanol, spec_drinks)
        return reduce(lambda x, y: x + y, ethanol_volumes, 0)

    @property
    def special_had(self):
        spec_drinks = self.drink_set.filter(special=True, date__year=date.today().year).values_list('beerinst__beer__id', flat=True)
        return len(spec_drinks)

    @property
    def special_due(self):
        # This year
        num_spec = self.drinks_unique_had / 10 # This is an implicit floor because int not float
        return num_spec - self.special_had

    @property
    def balance_dollars(self):
        return float(self.balance) / 100

    @property
    def current_drink(self):
        time_threshold = timezone.now() - timedelta(hours=1)
        return self.drink_set.filter(datetime__gt=time_threshold).order_by('-datetime').first()

    def reconcile(self):
        ### Needs to be all time, we carry debts over years.
        ###### We actually need the payee set now
        drinks = self.drink_payee_set.all().aggregate(debt=models.Sum('debt'))
        payments = self.payment_set.all().aggregate(value=models.Sum('value'))
        self.balance = (payments['value'] or 0) - (drinks['debt'] or 0)

    def clean(self):
        self.reconcile()

    def __unicode__(self):
        return "%s %s (%s)" % (self.user.first_name, self.user.last_name, self.user)

class Drink(models.Model):
    account = models.ForeignKey(Account)
    payee = models.ForeignKey(Account, related_name="drink_payee_set")
    beerinst = models.ForeignKey(BeerInst)
    special = models.BooleanField(blank=True, default=None)
    debt = models.IntegerField(blank=True,help_text="This is a value in AU cents. This value is populated automatically")
    date = models.DateField(auto_now_add=True, db_index=True)
    datetime = models.DateTimeField(auto_now_add=True, db_index=True)
    rating = models.PositiveIntegerField(null=True, default=3, blank=True)
    selfserve = models.BooleanField(default=False)

    class Meta:
        ordering = ["beerinst__beer__name"]
        get_latest_by = 'datetime'

    def clean(self):
        if self.rating > 5:
            self.rating = 5
        if self.special is None:
            self.special = self.beerinst.special
        if self.debt is None:
            if self.special is False:
                self.debt = self.beerinst.unit_sale_price
            else:
                self.debt = 0

    def __unicode__(self):
        msg = "%s -> %s" % (self.account.__unicode__(), self.beerinst.__unicode__())
        if self.special:
            msg = "%s SPECIAL" % (msg)
        if self.account != self.payee:
            msg = "%s paid for by %s" % (msg, self.payee.__unicode__())
        return msg

class Payment(models.Model):
    account = models.ForeignKey(Account)
    value = models.IntegerField(help_text="This is a value in AU cents")
    date = models.DateField(auto_now_add=True)

    def __unicode__(self):
        return "%s -> +%sc" % (self.account.__unicode__(), self.value)

class ClubAccount(models.Model):
    balance = models.IntegerField()

    def reconcile(self):
        on_hand = 0
        payment = Payment.objects.all().aggregate(value=models.Sum('value'))
        expenditure = Expenditure.objects.all().aggregate(cost=models.Sum('cost'))
        self.balance = (payment['value'] or 0) - (expenditure['cost'] or 0)
        self.save()

class Expenditure(models.Model):
    cost = models.IntegerField()
    comment = models.CharField(max_length=500)
    caccount = models.ForeignKey(ClubAccount)

    def __unicode__(self):
        return self.comment

def account_auto_reconcile(sender, **kwargs):
    instance = kwargs['instance']
    instance.account.reconcile()
    instance.account.save()

post_save.connect(account_auto_reconcile, sender=Drink)
post_save.connect(account_auto_reconcile, sender=Payment)

def stock_auto_reconcile(sender, **kwargs):

beerclub/forms.py
from django import forms
from beerclub.models import Drink

class DrinkForm(forms.Form):
    name = forms.CharField(max_length=255)
    payee_name = forms.CharField(max_length=255, required=False)
    beer = forms.CharField(max_length=255, required=False)
    name_pk = forms.IntegerField(initial=0)
    payee_name_pk = forms.IntegerField(initial=0, required=False)
    beer_pk = forms.IntegerField(initial=0)
    value = forms.CharField(initial=0, required=False)
    free = forms.BooleanField(required=False)
    special = forms.BooleanField(required=False)

class AccountCreateForm(forms.Form):
    name = forms.CharField(max_length=255)
    #name_pk = forms.IntegerField()
    #barcode = forms.CharField(max_length=255)

class StockCreateForm(forms.Form):
    barcode = forms.CharField(max_length=255, widget=(forms.TextInput(attrs={'autofocus':'autofocus'})))

beerclub/templates/beerclub/account_create.html
{% extends "uofa.html" %}

{% block content %}

    {{ form.non_field_errors }}
    <form method="post">
        {% csrf_token %}
        <div class="fieldWrapper">
            {{ form.name.errors }}
            <label for="id_name">Staff ID Number:</label>
            {{ form.name }}
        </div>
        <input type="submit" value="Induct!" class="btn btn-success"/>
    </form>

{% endblock %}

beerclub/templates/beerclub/account_list.html
{% extends "uofa.html" %}

{% block content %}


    <h2>Accounts</h2>

    <script>
        $(function() {
          $('#search_input').focus();
          $("#search_input").autocomplete({
            source: "/bc/api/get_names/",
            minLength: 2,
          });
        };);
    </script>
    {% if user.is_staff %}
    <form class="" method="get" action="" >
        <input id="search_input" type="text" name="search" placeholder="Search Account ...">
        <input type="submit" value="Search" class="btn btn-success"/>
    </form>
    {% endif %}


    <table class='table table-responsive table-striped' cellspacing="0" >
        <tr>
            <th style="width:250px">Name</th>
            <th style="width:20px">Drunk</th>
            <th style="width:20px">Unique drunk</th>
            <th style="width:20px">Special drunk</th>
            <th style="width:20px">Special due</th>
            <th style="width:60px">Balance</th>
        {% if user.is_staff %}
            <th style="width:200px">Payments</th>
        {% endif %}
        </tr>
        {% for account in object_list %}
            <tr> 
                <td>{{ account }}</td>
                <td>{{ account.drinks_had }}</td>
                <td>{{ account.drinks_unique_had }}</td>
                <td>{{ account.special_had }}</td>
                {% if account.special_due > 0 %}
                    <td style="background-color:yellow" >{{ account.special_due }}</td>
                {% else %}
                    <td>{{ account.special_due }}</td>
                {% endif %}

                {% if account.balance_dollars >= 0 %}
                    <td>{{ account.balance_dollars }}</td>
                {% else %}
                    <td style="background-color:pink">{{ account.balance_dollars }}</td>
                {% endif %}
                {% if user.is_staff %}
                    <td></td>
                {% endif %}
            <tr>
        {% endfor %}
    </table>
{% endblock %}

beerclub/templates/beerclub/beer_list.html
{% extends "uofa.html" %}

{% block content %}
    <h3>Beers</h3>

    <script src="/static/beerclub.js" async></script>
    <form class="noprint" method="get" action="{% url 'beerclub:beers' %}" >
        <input id="id_beer" type="text" name="search" placeholder="Search Beer ...">
        <input id="id_beer_pk" name="beer_pk" type="hidden" />
        <input type="submit" value="Search" class="btn btn-success"/>
    </form>

    {% if object_list %}
    <table class="table table-responsive table-striped">
        <tr>
            <th style="width:250px">Beer</th>
            <th style="width:20px">ABV</th>
            <th style="width:90px">Volume</th>
            <th style="width:150px">Brewery</th>
            <th style="width:150px">Country</th>
        {% if user.is_staff %}
            <th style="width:20px">Stock</th>
            <th style="width:400px">Who, When</th>
        {% endif %}
        </tr>
        <!-- This needs to filter on year -->
        {% for beerinst in object_list %}
            <tr> 
                {% if beerinst.special %}
                    <td style="background-color:yellow" >{{ beerinst.beer.name }}</td>
                {% else %}
                    <td>{{ beerinst.beer.name }}</td>
                {% endif %}
                <td>{{ beerinst.beer.abvp }}</td>
                <td>{{ beerinst.volume }}ml {{ beerinst.container }}</td>
                <td>{{ beerinst.beer.brewery }}</td>
                <td>{{ beerinst.beer.brewery.country }}</td>
                {% if user.is_staff %}
                <td>{{ beerinst.stock_total }}</td>
                <td>
                    {% for drink in beerinst.drink_set_year %}
                        {{ drink.account }}, {{ drink.date }}; </br>
                    {% endfor %}
                </td>
                {% endif %}
            <tr>
        {% endfor %}
    {% endif %}

{% endblock %}

beerclub/templates/beerclub/drink_create.html
{% extends "uofa.html" %}

{% block content %}

    <script src="/static/beerclub.js" async></script>


    {{ form.non_field_errors }}
    <form method="post" id="drink_form">
        {% csrf_token %}
        <div class="fieldWrapper form-group">
            {{ form.name_pk.errors }}
            {{ form.name_pk.as_hidden }}
            <label for="id_name">Name:</label>
            {{ form.name }}
        </div>
        <div class="fieldWrapper form-group">
            {{ form.beer_pk.errors }}
            {{ form.beer_pk.as_hidden }}
            <label for="id_beer">Beer:</label>
            {{ form.beer }}
        </div>
        <div class="fieldWrapper form-group">
            {{ form.value.errors }}
            <label for="id_value">Payment:</label>
            {{ form.value }}
        </div>
        <div id="showhide">
            <div class="fieldWrapper form-group">
                {{ form.payee_name_pk.errors }}
                {{ form.payee_name_pk.as_hidden }}
                <label for="id_payee_name">Payee Name:</label>
                {{ form.payee_name }}
            </div>
            <div class="fieldWrapper form-group">
                {{ form.free.errors }}
                <label for="id_free">Free:</label>
                {{ form.free }}
            </div>
            <div class="fieldWrapper form-group">
                {{ form.special.errors }}
                <label for="id_special">Special:</label>
                {{ form.special }}
            </div>
        </div>
        <input id="extras" type="button" value="Extras" class="btn btn-success"/>
        <input id="submit" type="submit" value="Drink!" class="btn btn-success"/>
    </form>

    <div id="account_stats">
        <table class='table table-striped' cellspacing="0" >
            <tr>
                <th style="width:20px">Drunk</th>
                <th style="width:20px">Unique drunk</th>
                <th style="width:20px">Special drunk</th>
                <th style="width:20px">Special due</th>
                <th style="width:60px">Balance</th>
            </tr>
            <tr>
                <td id="account_had"></td>
                <td id="account_unique_had"></td>
                <td id="account_special_had"></td>
                <td id="account_special_due"></td>
                <td id="account_balance"></td>
            </tr>
        </table>
    </div>
    <div id="account_unique">
        <table class='table table-striped' cellspacing="0" id="account_unique_table">
            <tr id="dontremove">
                <th style="min-width:60px">Name</th>
                <th style="min-width:20px">ABV</th>
                <th style="min-width:90px">Volume</th>
                <th style="min-width:150px">Brewery</th>
            </tr>
        </table>
    </div>



{% endblock %}

beerclub/templates/beerclub/history.html
{% extends "uofa.html" %}

{% block content %}

<h3>
The Beers, the Legends. Here they live, immortalised in data.
</h3>

{% for pastyear in pastyears %}
    <h4><a href="{% url 'beerclub:stats_year' year=pastyear.year %}">{{ pastyear.year }}</a></h4>
{% endfor %}

{% endblock %}

beerclub/templates/beerclub/legends_list.html
{% extends "uofa.html" %}

{% block content %}
    <h3>Accounts</h3>
    {% for account in object_list %}
    <h4>{{ account }}</h4>
    <table class="table table-striped"  style="text-align:left;font-size:10px">
        <tr>
            <th style="width:250px">Beer</th>
            <th style="width:20px">ABV</th>
            <th style="width:20px">Volume</th>
            <th style="width:150px">Brewery</th>
            <th style="width:150px">Country</th>
            <th style="width:10px">Special</th>
            <th style="width:100px">Date Drunk</th>
        </tr>
        <!-- This needs to filter on year -->
        {% for drink in account.drink_set.all %}
            <tr> 
                <td>{{ drink.beerinst.beer.name }}</td>
                <td>{{ drink.beerinst.beer.abvp }}</td>
                <td>{{ drink.beerinst.volume }}</td>
                <td>{{ drink.beerinst.beer.brewery }}</td>
                <td>{{ drink.beerinst.beer.brewery.country }}</td>
                <td>
                {% if drink.special %}
                    {{ drink.special }}
                {% elif drink.debt == 0 %}
                    Free
                {% endif %}
                </td>
                <td>{{ drink.date }}</td>
            <tr>
        {% endfor %}
        <!-- Add extra rows for filling in ... -->
        <tr><td>&nbsp;</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr><td>&nbsp;</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
    {% endfor %}
{% endblock %}

beerclub/templates/beerclub/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'accounts_login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

beerclub/templates/beerclub/root.html
{% extends "uofa.html" %}

{% block content %}

{% if user.account_set.all|length == 0 %}
<h2>What are you doing here stranger???</h2>
<h2>Go see the meisters in the staff room, friday evening</h2>
{% endif %}

{% endblock %}

beerclub/templates/beerclub/stats.html
{% extends "uofa.html" %}

{% block content %}

<h3>History of Beerclub: {{ year }} edition</h3>

<p>
Volume of beer: {{ total_volume }}L
</p>

<p>
Volume of ethanol: {{ total_ethanol }}L
</p>

<p>
Number of standard drinks: {{ std_drinks }}
</p>

<p>
{% for account in top_five %}
    {{ account }}<br />
{% endfor %}
</p>

{% if render_cash %}
    <p>
    Cash on hand: {{ caccount.balance }} AU Cents
    </p>
{% endif %}

{% endblock %}

beerclub/templates/beerclub/stock_create.html
{% extends "uofa.html" %}

{% block content %}

    <script src="/static/beerclub.js" async></script>

    {{ form.non_field_errors }}
    <form method="post" id="stock_form">
        {% csrf_token %}
        <div class="fieldWrapper">
            {{ form.barcode.errors }}
            <label for="id_barcode">Barcode:</label>
            {{ form.barcode }}
        </div>
        <input id="submit" type="submit" value="Submit" class="btn btn-success"/>
    </form>

{% endblock %}