beerclub/urls.py
from django.conf.urls import include, url
from beerclub.views import AccountListView, LegendsListView, BeerListView, DrinkCreateView, AccountCreateView, StockView, BeerUniqueListView, RootView, StatsView, HistoryView
from django.contrib.auth.decorators import login_required

from beerclub import rest as bc_rest

urlpatterns = [
    url(r'^accounts/$', AccountListView.as_view(), name='accounts'),
    url(r'^legends/$', LegendsListView.as_view(), name='legends' ),
    url(r'^beers/$', BeerListView.as_view(), name='beers' ),
    url(r'^beers/unique/$', BeerUniqueListView.as_view(), name='beers_unique' ),
    url(r'^drink/create/$', DrinkCreateView.as_view(), name='drink' ),
    url(r'^populate/$', AccountCreateView.as_view(), name='populate' ),
    url(r'^stock/import/$', StockView.as_view(), name='stockimport'),
    url(r'^stats/$', StatsView.as_view(), name='stats'),
    url(r'^stats/(?P<year>.+)/$', StatsView.as_view(), name='stats_year'),
    url(r'^history/$', HistoryView.as_view(), name='history'),
    # Django rest api
    # Definetly used
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/beer_list/', bc_rest.beer_list, name='beer_list'),
    url(r'^api/beer_search_instock/(?P<term>.+)/', bc_rest.beer_search_instock, name='beer_search_instock'),
    url(r'^api/beer_search/(?P<term>.+)/', bc_rest.beer_search, name='beer_search'),
    url(r'^api/beer_detail_barcode/(?P<barcode>.+)/', bc_rest.beer_detail_barcode, name='beer_detail_barcode'),
    url(r'^api/account_self_serve/', bc_rest.account_self_serve, name='account_self_serve'),
    url(r'^api/account/(?P<id>.+)/', bc_rest.account, name='account_id'),
    url(r'^api/account_unique_available/(?P<id>.+)/', bc_rest.account_unique_available, name='account_unique_available_id'),
    url(r'^api/account_drunk/(?P<acc_id>.+)/(?P<beer_id>.+)/', bc_rest.account_drunk, name='account_drunk'),
    url(r'^api/account_search/(?P<term>.+)/', bc_rest.account_search, name='account_search'),
    #Maybe unused?
    url(r'^api/account_unique_available/', bc_rest.account_unique_available, name='account_unique_available'),
    url(r'^api/account_random_unique/', bc_rest.account_random_unique, name='account_random_unique'),
    url(r'^api/account/', bc_rest.account, name='account'),
    url(r'^api/account_drinks/', bc_rest.account_drinks, name='account_drinks'),
    url(r'^api/beer_detail/(?P<id>.+)/', bc_rest.beer_detail, name='beer_detail'),
    url(r'^api/account_current_drink/', bc_rest.account_current_drink, name='account_current_drink'),
    url(r'^api/account_current_drink_rating/', bc_rest.account_current_drink_rating, name='account_current_drink_rating'),
    # Root view
    url(r'^', RootView.as_view(), name='root'),
]

its_django/urls.py
from django.conf.urls import include, url

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
admin.autodiscover()
#from django.views.generic import TemplateView
from beerclub.views import RootView

urlpatterns = [
    # Examples:
    # url(r'^$', 'its_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/', auth_views.login, {'template_name': 'beerclub/login.html', 'extra_context': {'next':'/bc/'} }, name="accounts_login"),
    url(r'^accounts/logout/', auth_views.logout, {'next_page': '/', 'template_name': 'beerclub/logout.html'}, name="accounts_logout"),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^bc/', include('beerclub.urls', namespace='beerclub')),
    url(r'^', include('beerclub.urls', namespace='beerclub_root')),
    #url(r'^$', 'django.contrib.auth.views.login', {'template_name': 'beerclub/login.html', 'extra_context': {'next':'/bc/'} }, name="root_accounts_login"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    #urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beerclub/forms.py
from django import forms
from beerclub.models import Drink

class DrinkForm(forms.Form):
    name = forms.CharField(max_length=255)
    payee_name = forms.CharField(max_length=255, required=False)
    beer = forms.CharField(max_length=255, required=False)
    name_pk = forms.IntegerField(initial=0)
    payee_name_pk = forms.IntegerField(initial=0, required=False)
    beer_pk = forms.IntegerField(initial=0)
    value = forms.CharField(initial=0, required=False)
    free = forms.BooleanField(required=False)
    special = forms.BooleanField(required=False)

class AccountCreateForm(forms.Form):
    name = forms.CharField(max_length=255)
    #name_pk = forms.IntegerField()
    #barcode = forms.CharField(max_length=255)

class StockCreateForm(forms.Form):
    barcode = forms.CharField(max_length=255, widget=(forms.TextInput(attrs={'autofocus':'autofocus'})))

beerclub/views.py
import json
import re

from datetime import date, timedelta

from django.http import HttpResponseForbidden
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django_auth_ldap.backend import LDAPBackend
from django.views.generic import ListView, TemplateView, FormView, CreateView, UpdateView
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required

from django.contrib.auth.mixins import LoginRequiredMixin

from django.db import models

from beerclub.models import Account, Beer, Drink, Payment, BeerInst, Stock, ClubAccount
from beerclub.forms import DrinkForm, AccountCreateForm, StockCreateForm

from functools import partial
# Create your views here.

class RootView(LoginRequiredMixin, TemplateView):
    template_name = 'beerclub/root.html'

    #@method_decorator(permission_required('beerclub.can_login', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(RootView, self).dispatch(*args, **kwargs)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = 'beerclub/account_list.html'

    def get_queryset(self):
        if not self.request.user.is_staff:
            return self.model.objects.filter(user=self.request.user)
        return self.model.objects.all()

    def get_queryset(self):
        if self.request.GET.has_key('search') and self.request.user.is_staff:
            search = self.request.GET['search']
            return self.model.objects.filter( Q(user__username__icontains=search) |
                Q(user__first_name__icontains=search) |
                Q(user__last_name__icontains=search) )
        elif self.request.user.is_staff:
            return self.model.objects.all()
        else:
            return self.model.objects.filter(user=self.request.user)

    #@method_decorator(permission_required('beerclub.can_login', raise_exception=True))
    def dispatch(self, *args, **kwargs):
        return super(AccountListView, self).dispatch(*args, **kwargs)

class LegendsListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = 'beerclub/legends_list.html'

    def get_queryset(self):
        if not self.request.user.is_staff:
            return HttpResponseForbidden()
            #return self.model.objects.filter(user=self.request.user)
        return self.model.objects.all()

    #@method_decorator(permission_required('beerclub.can_login', raise_exception=True))
    #def dispatch(self, *args, **kwargs):
    #    return super(LegendsListView, self).dispatch(*args, **kwargs)

class BeerListView(LoginRequiredMixin, ListView):
    model = BeerInst
    template_name = 'beerclub/beer_list.html'

    def get_queryset(self):
        if self.request.GET.has_key('search'):
            search = self.request.GET['search']
            try:
                beerinst_pk = int(self.request.GET['beer_pk'])
            except:
                beerinst_pk = 0
            return self.model.objects.filter(Q(beer__name__icontains=search) | Q(beer__brewery__name__icontains=search) | Q(barcode=search) | Q(barcode_pack=search) | Q(pk=beerinst_pk))
        else:
            #return self.model.objects.all()
            return None

    #@method_decorator(permission_required('beerclub.can_login', raise_exception=True))
    #def dispatch(self, *args, **kwargs):
    #    return super(BeerListView, self).dispatch(*args, **kwargs)

class BeerUniqueListView(LoginRequiredMixin, ListView):
    model = BeerInst
    template_name = 'beerclub/beer_list.html'

    def get_queryset(self):
        account = Account.objects.get(user=self.request.user)
        spec_drinks = account.drink_set.filter(date__year=date.today().year).values_list('beerinst__beer__id', flat=True).distinct()
        available_beers = BeerInst.objects.filter(stock_total__gt=0)
        available = filter(lambda x: x.beer.id not in spec_drinks, available_beers)
        return sorted(available, cmp=lambda a,b: a.beer.name < b.beer.name)

    #@method_decorator(permission_required('beerclub.can_login', raise_exception=True))
    #def dispatch(self, *args, **kwargs):
    #    return super(BeerUniqueListView, self).dispatch(*args, **kwargs)

class DrinkCreateView(LoginRequiredMixin, FormView):
    template_name = 'beerclub/drink_create.html'
    form_class = DrinkForm
    success_url = "/bc/drink/create/"

    #@method_decorator(permission_required('beerclub.can_login', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden()
        return super(DrinkCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        data = form.cleaned_data
        account_id = data.get('name_pk', 0)
        if account_id != 0:
            account = Account.objects.get(pk=account_id)
        else:
            messages.error(self.request, "Invalid account")
            return super(DrinkCreateView, self).form_invalid(form)
        beer_id = data.get('beer_pk', 0)
        payee_id = data.get('payee_name_pk', 0)
        translation_table = dict.fromkeys(map(ord, '$.'), None)
        value = data.get('value', 0).translate(translation_table)
        if value == 0:
            #### Do nothing
            pass
        elif value < 0:
            messages.error(self.request, "Cannot add negative payment")
        else:
            payment = Payment(account=account, value=value, date=date.today())
            payment.clean()
            payment.save()
            messages.success(self.request, 'Payment added! %s' % payment)
        ### Drink sales
        try:
            if beer_id != 0:
                beerinst = BeerInst.objects.get(pk=beer_id)
                drink = create_drink_sale(account, beerinst, data['free'], data['special'], payee_id=payee_id)
                messages.success(self.request, 'Drink added! %s' % drink)
        except Exception as e:
            messages.error(self.request, e)
        return super(DrinkCreateView, self).form_valid(form)

class AccountCreateView(LoginRequiredMixin, FormView):
    template_name = 'beerclub/account_create.html'
    form_class = AccountCreateForm
    success_url = "/bc/accounts"

    #@method_decorator(permission_required('beerclub.can_login', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden()
        return super(AccountCreateView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        data = form.cleaned_data
        name = data.get('name', None)
        #barcode = data.get('barcode', None)
        if name is not None:
            user = None
            try:
                user = User.objects.get(username=name)
            except:
                ldapobj = LDAPBackend()
                user = ldapobj.populate_user(name)
                if user is not None and not user.is_anonymous():
                    print("%s -> True" % name)
                else:
                    print("%s -> False" % name)
                user.save()
            account = None
            try:
                account = Account.objects.get(user=user)
            except:
                account = Account(user=user, balance=0)
            print("Creating %s" % user)
            #account.barcode = barcode
            account.save()
            messages.success(self.request, "Added %s" % user)
        return super(AccountCreateView, self).form_valid(form)

class StockView(LoginRequiredMixin, FormView):
    template_name = 'beerclub/stock_create.html'
    form_class = StockCreateForm
    success_url = '/bc/stock/import/'

    def stock_import(self, beerinst, quantity):
        si = Stock(beerinst=beerinst, quantity=quantity)
        si.clean()
        si.save()
        messages.success(self.request, 'Beer added %s : %s' % (beerinst, quantity))

    #@method_decorator(permission_required('beerclub.can_login', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden()
        return super(StockView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        data = form.cleaned_data
        barcode = data.get('barcode', None)
        beerinst_pack = BeerInst.objects.filter(barcode_pack=barcode).first()
        beerinst_sing = BeerInst.objects.filter(barcode=barcode).first()
        if beerinst_pack is not None:
            self.stock_import(beerinst_pack, beerinst_pack.quantity_pack)
        elif beerinst_sing is not None:
            self.stock_import(beerinst_sing, 1)
        else:
            print('NO SUCH BEER')
            messages.error(self.request, 'No such barcode')
        return super(StockView, self).form_valid(form)

class StatsView(LoginRequiredMixin, TemplateView):
    template_name = 'beerclub/stats.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden()
        return super(StatsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        stat_year = date.today().year
        render_cash = True
        if 'year' in kwargs:
            stat_year = date(year=int(kwargs['year']), month=1, day=1).year
            render_cash = False
        context = super(StatsView, self).get_context_data(**kwargs)
        context['render_cash'] = render_cash
        year_drinks = Drink.objects.filter(date__year=stat_year)
        accounts = Account.objects.all()

beerclub/templates/base.html
{% load staticfiles %}

<!DOCTYPE html> 

<html lang="en">
    <head>
    </head>

    <body>
        {% if not user.is_anonymous %}
            <a href="{% url 'accounts_logout' %}">Logout</a>
            {% if user.is_staff %}
                <a href="/admin/">Admin</a>
            {% endif %}
        {% endif %}

        {% block content %}
        <p>Template</p>
        {% endblock %}
    </body>

</html>

beerclub/templates/uofa.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
    <!-- UA Web Team Template v2.0 -->
    <title>
        {% block title %}
        {% endblock %}
    </title>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <link href="{% static 'jquery-ui-1.11.0/jquery-ui.min.css' %}" rel="stylesheet" >
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'jquery-ui-1.11.0/jquery-ui.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.inputmask.bundle.js' %}"></script>

</head>

<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <!-- Do I need as many of these as items ... ? -->
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="">
                    <img src="/static/sub-crux-beeren.png" alt="The University of Adelaide Australia" title="The University of Adelaide Australia" height=30>
                </a>
            </div> <!-- end navbar-header -->
            <div class="navbar-collapse collapse navbar-left navbar-form">
                <form method="get" action="" >
                    <a class="btn btn-success navbar-btn" href="{% url 'beerclub:accounts' %}">Accounts</a>
                    <a class="btn btn-success navbar-btn" href="{% url 'beerclub:beers_unique' %}">Unique Beer List</a>
                    {% if user.is_staff %}
                    <a class="btn btn-success navbar-btn" href="{% url 'beerclub:drink' %}">Serve drinks</a>
                    <a class="btn btn-success navbar-btn" href="{% url 'beerclub:populate' %}">Populate account</a>
                    <a class="btn btn-success navbar-btn" href="{% url 'beerclub:legends' %}">Legends</a>
                    <a class="btn btn-success navbar-btn" href="{% url 'beerclub:beers' %}">Beer List</a>
                    {% endif %}
                </form>
            </div>
            <div class="navbar-collapse collapse navbar-form navbar-right">
                <form method="get" action="" >
                    {% if user.is_staff %}
                    <a class="btn btn-success navbar-btn" href="{% url 'beerclub:stockimport' %}">Import Stock</a>
                    <a class="btn btn-success navbar-btn" href="{% url 'beerclub:stats' %}">Stats</a>
                    <a class="btn btn-success navbar-btn" href="{% url 'beerclub:history' %}">History</a>
                    <a class="btn btn-success navbar-btn" href="/admin/">Admin</a>
                    {% endif %}
                    <a class="btn btn-success navbar-btn" href="{% url 'accounts_logout' %}">Logout</a>
                </form>
            </div> <!-- end collapse -->
        </div> <!-- end container -->
    </div> <!-- End navbar -->


    <div class="main" style="padding-top: 50px;">
        {% if messages %}

        <ul class="messages alert alert-warning">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %} >{{ message }}</li>
        {% endfor %}
        </ul>
        {% endif %}

         <div id="block_content">
         {% block content %}
         {% endblock %}
         </div>
     </div>

</body>
</html>